server:
  servlet:
    context-path: /shbp
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
          batch_size: 10
          order_inserts: true
        generate_statistics: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password: sa
    driverClassName: org.h2.Driver