DROP TABLE DOG;
DROP TABLE PERSON_DETAILS;
DROP TABLE PERSON_JOB;
DROP TABLE JOB;
DROP TABLE PERSON;

CREATE TABLE IF NOT EXISTS PERSON (
   id INT NOT NULL,
   name VARCHAR(50) NOT NULL,
   created TIMESTAMP NOT NULL,
   updated TIMESTAMP NOT NULL,
   version INT NOT NULL
);

CREATE TABLE IF NOT EXISTS PERSON_DETAILS (
   id INT NOT NULL,
   details VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS DOG (
   id INT NOT NULL,
   name VARCHAR(50) NOT NULL,
   breed VARCHAR(50) NOT NULL,
   person INT NOT NULL,
   version INT NOT NULL
);

CREATE TABLE IF NOT EXISTS JOB (
   id INT NOT NULL,
   name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS PERSON_JOB (
   person INT NOT NULL,
   job INT NOT NULL
);