DROP TABLE DOG;
DROP TABLE PERSON;

CREATE TABLE IF NOT EXISTS PERSON (
   id INT NOT NULL,
   name VARCHAR(50) NOT NULL,
   created TIMESTAMP NOT NULL,
   updated TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS DOG (
   id INT NOT NULL,
   name VARCHAR(50) NOT NULL,
   breed VARCHAR(50) NOT NULL,
   person INT NOT NULL
);